name = "openwebosapi"
main = "worker.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[triggers]
routes = [
  { pattern = "openwebosapi.*.workers.dev", custom_domain = false }
]

[vars]
API_VERSION = "3.0.0"
