name = "openwebos-api"
main = "worker.js"
compatibility_date = "2024-01-01"

[triggers]
routes = [
  { pattern = "openwebos-api.*.workers.dev", custom_domain = false }
]

[env.production]
workers_dev = true

[vars]
API_VERSION = "1.0.0"
